apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-container
        image: muralisocial123/python-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1 
kind: Service
metadata:
  name: app-deployment-svc
spec:
  selector:
    app: python
  ports:
  - port: 5004
    targetPort: 5000
  type: ClusterIP 
        
