apiVersion: apps/v1
kind: Deployment
metadata:
  name: trans-deployment 
spec:
  relicas: 4
  selector:
    matchLabels:
      app: trans
  template:
    metadata:
      labels:
        app: trans
    spec:
      containers:
        - name: trannsaction-cont
          image: muralisocial123/transcation-image:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1 
kind: Service
metadata:
  name: trans-svc
spec:
  selector:
    app: trans
  ports:
  - port: 3005
    targetPort: 3000
  type: ClusterIP  
        
